# OSCAR HERNANDEZ GOMEZ (70919457S) - GRUPO A1
# Práctica final
prueba: prueba.c dispersion.o
	gcc -g prueba.c dispersion.o -o prueba
dispersion.o: dispersion.h dispersion.c
	gcc -c -g dispersion.c -o dispersion.o
clean:
	rm *.o